<?php

declare(strict_types=1);

use Xizhen\Core\Container;
use Xizhen\Core\Middleware\AdminAuthMiddleware;
use Xizhen\Core\Middleware\CsrfMiddleware;
use Xizhen\Core\Middleware\TenantAuthMiddleware;
use Xizhen\Core\Router;
use Xizhen\Http\Controllers\Admin\AdminController;
use Xizhen\Http\Controllers\Tenant\AuthController;
use Xizhen\Http\Controllers\Tenant\DashboardController;
use Xizhen\Http\Controllers\Tenant\ImportExportController;
use Xizhen\Http\Controllers\Tenant\LogisticsController;
use Xizhen\Http\Controllers\Tenant\MailController;
use Xizhen\Http\Controllers\Tenant\OrderAjaxController;
use Xizhen\Http\Controllers\Tenant\OrderController;
use Xizhen\Http\Controllers\Tenant\OrderExportController;
use Xizhen\Http\Controllers\Tenant\SettingsController;
use Xizhen\Http\Controllers\Tenant\StatsController;
use Xizhen\Http\Controllers\Tenant\StoreController;
use Xizhen\Http\Controllers\Tenant\UserController;

return static function (Container $container, Router $router): void {
    $router->middleware([CsrfMiddleware::class]);

    $router->get('/admin/login', [AdminController::class, 'loginForm']);
    $router->post('/admin/login', [AdminController::class, 'login']);
    $router->post('/admin/logout', [AdminController::class, 'logout']);
    $router->group([AdminAuthMiddleware::class], static function (Router $router): void {
        $router->get('/admin', [AdminController::class, 'overview']);
        $router->get('/admin/tenants', [AdminController::class, 'tenants']);
        $router->get('/admin/tenants/create', [AdminController::class, 'tenantCreateForm']);
        $router->post('/admin/tenants/create', [AdminController::class, 'tenantCreate']);
        $router->get('/admin/billing', [AdminController::class, 'billing']);
        $router->post('/admin/billing/adjust', [AdminController::class, 'adjustBilling']);
        $router->post('/admin/billing/process', [AdminController::class, 'processBilling']);
        $router->get('/admin/platforms', [AdminController::class, 'platforms']);
        $router->post('/admin/platforms/toggle', [AdminController::class, 'togglePlatform']);
        $router->post('/admin/features/toggle', [AdminController::class, 'toggleFeature']);
        $router->get('/admin/announcements', [AdminController::class, 'announcements']);
        $router->get('/admin/settings', [AdminController::class, 'settings']);
        $router->post('/admin/settings/save', [AdminController::class, 'saveSettings']);
        $router->get('/admin/system', [AdminController::class, 'systemStatus']);
    });
    $router->get('/login', [AuthController::class, 'loginForm']);
    $router->post('/login', [AuthController::class, 'login']);
    $router->post('/logout', [AuthController::class, 'logout']);
    $router->group([TenantAuthMiddleware::class], static function (Router $router): void {
        $router->get('/', [DashboardController::class, 'dashboard']);
        $router->get('/orders', [OrderController::class, 'orders']);
        $router->get('/orders/detail', [OrderController::class, 'orderDetail']);
        $router->post('/orders/source', [OrderController::class, 'changeSource']);
        $router->post('/orders/batch', [OrderController::class, 'batchOrders']);
        $router->post('/orders/export', [OrderExportController::class, 'exportOrders']);
        $router->post('/orders/send-jp', [OrderExportController::class, 'sendJapan']);
        $router->post('/orders/xizhen-delivery/export', [OrderExportController::class, 'exportXizhenDelivery']);
        $router->post('/orders/logistics/update', [OrderExportController::class, 'updateLogistics']);
        $router->post('/orders/platform/sync', [OrderExportController::class, 'syncPlatformOrders']);
    });
    $router->post('/orders/rakuten/sync', [OrderExportController::class, 'syncRakutenOrders']);
    $router->group([TenantAuthMiddleware::class], static function (Router $router): void {
        $router->post('/orders/item/save', [OrderController::class, 'saveOrderItem']);
        $router->post('/orders/attachments/add', [OrderController::class, 'addOrderAttachment']);
        $router->post('/orders/attachments/delete', [OrderController::class, 'deleteOrderAttachment']);
        $router->post('/orders/images/upload', [OrderController::class, 'uploadOrderImage']);
        $router->get('/features', [DashboardController::class, 'features']);
        $router->get('/search', [DashboardController::class, 'search']);
        $router->get('/analytics/profit', [StatsController::class, 'profit']);
        $router->get('/performance', [StatsController::class, 'performanceDashboard']);
        $router->get('/performance/daily-data', [StatsController::class, 'performanceDailyData']);
        $router->get('/performance/summary', [StatsController::class, 'performanceSummary']);
        $router->get('/performance/products', [StatsController::class, 'productAnalysis']);
        $router->get('/performance/products-data', [StatsController::class, 'productAnalysisData']);
        $router->get('/price-calculator', [StatsController::class, 'priceCalculator']);
        $router->post('/price-calculator/calculate', [StatsController::class, 'calculatePrice']);
        $router->get('/stats/purchase', [StatsController::class, 'purchaseStats']);
        $router->get('/stats/purchase/status-daily', [StatsController::class, 'purchaseStatusDaily']);
        $router->get('/stats/shipping-anomaly', [StatsController::class, 'shippingAnomaly']);
        $router->get('/logistics/1688', [LogisticsController::class, 'logistics1688']);
        $router->get('/logistics/express', [LogisticsController::class, 'logisticsExpress']);
        $router->get('/logistics/jp', [LogisticsController::class, 'logisticsJp']);
        $router->get('/logistics/waybill-check', [LogisticsController::class, 'waybillCheck']);
        $router->get('/logistics/jpyd-check', [LogisticsController::class, 'jpydCheck']);
        $router->get('/mail', [MailController::class, 'mail']);
        $router->get('/mail/settings', [MailController::class, 'mailSettings']);
        $router->get('/mail/rules', [MailController::class, 'mailRules']);
        $router->post('/mail/accounts/save', [MailController::class, 'saveMailAccount']);
        $router->post('/mail/accounts/delete', [MailController::class, 'deleteMailAccount']);
        $router->post('/mail/folders/probe', [MailController::class, 'probeMailFolders']);
        $router->post('/mail/folders/save', [MailController::class, 'saveMailFolder']);
        $router->post('/mail/sync', [MailController::class, 'syncMail']);
        $router->post('/mail/action', [MailController::class, 'mailAction']);
        $router->post('/mail/move', [MailController::class, 'moveMail']);
        $router->post('/mail/rules/save', [MailController::class, 'saveMailRule']);
        $router->post('/mail/rules/delete', [MailController::class, 'deleteMailRule']);
        $router->post('/mail/rules/apply', [MailController::class, 'applyMailRules']);
        $router->post('/mail/reply', [MailController::class, 'replyMail']);
        $router->get('/import-export', [ImportExportController::class, 'importExport']);
        $router->get('/import-export/non-excel', [ImportExportController::class, 'importExportNonExcel']);
        $router->get('/import-export/export', [ImportExportController::class, 'exportCsv']);
        $router->get('/import-export/platform-special/export', [ImportExportController::class, 'exportPlatformSpecial']);
        $router->get('/import-export/export-templates/edit', [ImportExportController::class, 'exportTemplateEdit']);
        $router->post('/import-export/export-templates/save', [ImportExportController::class, 'saveExportTemplate']);
        $router->post('/import-export/export-templates/delete', [ImportExportController::class, 'deleteExportTemplate']);
        $router->post('/import-export/export-templates/preview', [ImportExportController::class, 'previewExportTemplate']);
        $router->get('/import-export/customers/export', [ImportExportController::class, 'exportCustomers']);
        $router->get('/import-export/finance-placeholder/export', [ImportExportController::class, 'exportFinancePlaceholder']);
        $router->get('/import-export/brush-orders/export', [ImportExportController::class, 'exportBrushOrders']);
        $router->post('/import-export/import', [ImportExportController::class, 'importCsv']);
        $router->post('/import-export/finance-import/preview', [ImportExportController::class, 'previewFinanceImport']);
        $router->post('/import-export/finance-import/import', [ImportExportController::class, 'importFinanceData']);
        $router->post('/import-export/shipping-modes/preview', [ImportExportController::class, 'previewShippingImportModes']);
        $router->post('/import-export/shipping-modes/import', [ImportExportController::class, 'importShippingModes']);
        $router->post('/import-export/jp-warehouse/preview', [ImportExportController::class, 'previewJapanWarehouseImport']);
        $router->post('/import-export/jp-warehouse/import', [ImportExportController::class, 'importJapanWarehouse']);
        $router->post('/import-export/external-insert/preview', [ImportExportController::class, 'externalInsertPreview']);
        $router->post('/import-export/external-insert/import', [ImportExportController::class, 'externalInsertImport']);
        $router->get('/media', [SettingsController::class, 'media']);
        $router->get('/jobs', [SettingsController::class, 'jobs']);
        $router->get('/logs', [SettingsController::class, 'logs']);
        $router->get('/billing', [SettingsController::class, 'billing']);
        $router->get('/settings', [SettingsController::class, 'settings']);
        $router->post('/settings/save', [SettingsController::class, 'saveSettings']);
        $router->post('/settings/purchase-statuses/save', [SettingsController::class, 'savePurchaseStatuses']);
        $router->get('/stores', [StoreController::class, 'stores']);
        $router->post('/stores/add', [StoreController::class, 'addStore']);
        $router->get('/stores/import', [StoreController::class, 'importOrdersForm']);
        $router->post('/stores/import', [StoreController::class, 'importOrders']);
        $router->get('/stores/edit', [StoreController::class, 'editStore']);
        $router->post('/stores/update', [StoreController::class, 'updateStore']);
        $router->get('/stores/yahoo/authorize', [StoreController::class, 'authorizeYahooShop']);
    });
    $router->get('/oauth/yahoo/callback', [StoreController::class, 'yahooOAuthCallback']);
    $router->group([TenantAuthMiddleware::class], static function (Router $router): void {
        $router->get('/users', [UserController::class, 'users']);
        $router->post('/users/add', [UserController::class, 'addUser']);
        $router->get('/users/edit', [UserController::class, 'editUser']);
        $router->post('/users/update', [UserController::class, 'updateUser']);
        $router->get('/password/edit', [AuthController::class, 'passwordEdit']);
        $router->post('/password/update', [AuthController::class, 'passwordUpdate']);
        $router->get('/notices', [SettingsController::class, 'tenantNotices']);
        $router->get('/notices/edit', [SettingsController::class, 'tenantNotices']);
        $router->post('/notices/save', [SettingsController::class, 'saveTenantNotice']);
        $router->post('/notices/delete', [SettingsController::class, 'deleteTenantNotice']);
        $router->post('/notices/pin', [SettingsController::class, 'pinTenantNotice']);
        $router->get('/users/permissions', [UserController::class, 'userPermissions']);
        $router->post('/users/permissions/save', [UserController::class, 'saveUserPermissions']);
        $router->get('/users/customer-service-deductions', [UserController::class, 'customerServiceDeductions']);
        $router->post('/users/customer-service-deductions/save', [UserController::class, 'saveCustomerServiceDeductions']);
        $router->get('/assignments', [UserController::class, 'assignments']);
        $router->post('/assignments/save', [UserController::class, 'saveAssignment']);
        $router->get('/orders/ajax/row', [OrderAjaxController::class, 'ajaxOrderRow']);
        $router->get('/orders/ajax/detail', [OrderAjaxController::class, 'ajaxOrderDetail']);
        $router->get('/orders/ajax/logistics', [OrderAjaxController::class, 'ajaxLogisticsReload']);
        $router->post('/orders/ajax/review', [OrderAjaxController::class, 'ajaxToggleReview']);
    });
};
