<?php

declare(strict_types=1);

use Xizhen\Core\Config;
use Xizhen\Core\Router;
use Xizhen\Core\StoreInterface;
use Xizhen\Core\View;
use Xizhen\Http\Controllers\Admin\AdminController;
use Xizhen\Http\Controllers\Tenant\AuthController;
use Xizhen\Http\Controllers\Tenant\DashboardController;
use Xizhen\Http\Controllers\Tenant\ImportExportController;
use Xizhen\Http\Controllers\Tenant\LogisticsController;
use Xizhen\Http\Controllers\Tenant\MailController;
use Xizhen\Http\Controllers\Tenant\OrderAjaxController;
use Xizhen\Http\Controllers\Tenant\OrderController;
use Xizhen\Http\Controllers\Tenant\OrderExportController;
use Xizhen\Http\Controllers\Tenant\SettingsController;
use Xizhen\Http\Controllers\Tenant\StatsController;
use Xizhen\Http\Controllers\Tenant\StoreController;
use Xizhen\Http\Controllers\Tenant\UserController;
use Xizhen\Services\AuthService;

return static function (Router $router, StoreInterface $store, View $view, Config $config, AuthService $auth): void {
    $admin = new AdminController($store, $view, $config, $auth);
    $authController = new AuthController($store, $view, $auth);
    $dashboardController = new DashboardController($store, $view, $auth);
    $orderController = new OrderController($store, $view, $auth);
    $orderExportController = new OrderExportController($store, $view, $auth);
    $orderAjaxController = new OrderAjaxController($store, $view, $auth);
    $logisticsController = new LogisticsController($store, $view, $auth);
    $mailController = new MailController($store, $view, $auth);
    $importExportController = new ImportExportController($store, $view, $auth);
    $statsController = new StatsController($store, $view, $auth);
    $storeController = new StoreController($store, $view, $auth);
    $userController = new UserController($store, $view, $auth);
    $settingsController = new SettingsController($store, $view, $auth);

    $router->get('/admin/login', [$admin, 'loginForm']);
    $router->post('/admin/login', [$admin, 'login']);
    $router->post('/admin/logout', [$admin, 'logout']);
    $router->get('/admin', [$admin, 'overview']);
    $router->get('/admin/tenants', [$admin, 'tenants']);
    $router->get('/admin/tenants/create', [$admin, 'tenantCreateForm']);
    $router->post('/admin/tenants/create', [$admin, 'tenantCreate']);
    $router->get('/admin/billing', [$admin, 'billing']);
    $router->post('/admin/billing/adjust', [$admin, 'adjustBilling']);
    $router->post('/admin/billing/process', [$admin, 'processBilling']);
    $router->get('/admin/platforms', [$admin, 'platforms']);
    $router->post('/admin/platforms/toggle', [$admin, 'togglePlatform']);
    $router->post('/admin/features/toggle', [$admin, 'toggleFeature']);
    $router->get('/admin/announcements', [$admin, 'announcements']);
    $router->get('/admin/settings', [$admin, 'settings']);
    $router->post('/admin/settings/save', [$admin, 'saveSettings']);
    $router->get('/admin/system', [$admin, 'systemStatus']);
    $router->get('/login', [$authController, 'loginForm']);
    $router->post('/login', [$authController, 'login']);
    $router->post('/logout', [$authController, 'logout']);
    $router->get('/', [$dashboardController, 'dashboard']);
    $router->get('/orders', [$orderController, 'orders']);
    $router->get('/orders/detail', [$orderController, 'orderDetail']);
    $router->post('/orders/source', [$orderController, 'changeSource']);
    $router->post('/orders/batch', [$orderController, 'batchOrders']);
    $router->post('/orders/export', [$orderExportController, 'exportOrders']);
    $router->post('/orders/send-jp', [$orderExportController, 'sendJapan']);
    $router->post('/orders/xizhen-delivery/export', [$orderExportController, 'exportXizhenDelivery']);
    $router->post('/orders/logistics/update', [$orderExportController, 'updateLogistics']);
    $router->post('/orders/platform/sync', [$orderExportController, 'syncPlatformOrders']);
    $router->post('/orders/rakuten/sync', [$orderExportController, 'syncRakutenOrders']);
    $router->post('/orders/item/save', [$orderController, 'saveOrderItem']);
    $router->post('/orders/attachments/add', [$orderController, 'addOrderAttachment']);
    $router->post('/orders/attachments/delete', [$orderController, 'deleteOrderAttachment']);
    $router->post('/orders/images/upload', [$orderController, 'uploadOrderImage']);
    $router->get('/features', [$dashboardController, 'features']);
    $router->get('/search', [$dashboardController, 'search']);
    $router->get('/analytics/profit', [$statsController, 'profit']);
    $router->get('/performance', [$statsController, 'performanceDashboard']);
    $router->get('/performance/daily-data', [$statsController, 'performanceDailyData']);
    $router->get('/performance/summary', [$statsController, 'performanceSummary']);
    $router->get('/performance/products', [$statsController, 'productAnalysis']);
    $router->get('/performance/products-data', [$statsController, 'productAnalysisData']);
    $router->get('/price-calculator', [$statsController, 'priceCalculator']);
    $router->post('/price-calculator/calculate', [$statsController, 'calculatePrice']);
    $router->get('/stats/purchase', [$statsController, 'purchaseStats']);
    $router->get('/stats/purchase/status-daily', [$statsController, 'purchaseStatusDaily']);
    $router->get('/stats/shipping-anomaly', [$statsController, 'shippingAnomaly']);
    $router->get('/logistics/1688', [$logisticsController, 'logistics1688']);
    $router->get('/logistics/express', [$logisticsController, 'logisticsExpress']);
    $router->get('/logistics/jp', [$logisticsController, 'logisticsJp']);
    $router->get('/logistics/waybill-check', [$logisticsController, 'waybillCheck']);
    $router->get('/logistics/jpyd-check', [$logisticsController, 'jpydCheck']);
    $router->get('/mail', [$mailController, 'mail']);
    $router->get('/mail/settings', [$mailController, 'mailSettings']);
    $router->get('/mail/rules', [$mailController, 'mailRules']);
    $router->post('/mail/accounts/save', [$mailController, 'saveMailAccount']);
    $router->post('/mail/accounts/delete', [$mailController, 'deleteMailAccount']);
    $router->post('/mail/folders/probe', [$mailController, 'probeMailFolders']);
    $router->post('/mail/folders/save', [$mailController, 'saveMailFolder']);
    $router->post('/mail/sync', [$mailController, 'syncMail']);
    $router->post('/mail/action', [$mailController, 'mailAction']);
    $router->post('/mail/move', [$mailController, 'moveMail']);
    $router->post('/mail/rules/save', [$mailController, 'saveMailRule']);
    $router->post('/mail/rules/delete', [$mailController, 'deleteMailRule']);
    $router->post('/mail/rules/apply', [$mailController, 'applyMailRules']);
    $router->post('/mail/reply', [$mailController, 'replyMail']);
    $router->get('/import-export', [$importExportController, 'importExport']);
    $router->get('/import-export/non-excel', [$importExportController, 'importExportNonExcel']);
    $router->get('/import-export/export', [$importExportController, 'exportCsv']);
    $router->get('/import-export/platform-special/export', [$importExportController, 'exportPlatformSpecial']);
    $router->get('/import-export/export-templates/edit', [$importExportController, 'exportTemplateEdit']);
    $router->post('/import-export/export-templates/save', [$importExportController, 'saveExportTemplate']);
    $router->post('/import-export/export-templates/delete', [$importExportController, 'deleteExportTemplate']);
    $router->post('/import-export/export-templates/preview', [$importExportController, 'previewExportTemplate']);
    $router->get('/import-export/customers/export', [$importExportController, 'exportCustomers']);
    $router->get('/import-export/finance-placeholder/export', [$importExportController, 'exportFinancePlaceholder']);
    $router->get('/import-export/brush-orders/export', [$importExportController, 'exportBrushOrders']);
    $router->post('/import-export/import', [$importExportController, 'importCsv']);
    $router->post('/import-export/finance-import/preview', [$importExportController, 'previewFinanceImport']);
    $router->post('/import-export/finance-import/import', [$importExportController, 'importFinanceData']);
    $router->post('/import-export/shipping-modes/preview', [$importExportController, 'previewShippingImportModes']);
    $router->post('/import-export/shipping-modes/import', [$importExportController, 'importShippingModes']);
    $router->post('/import-export/jp-warehouse/preview', [$importExportController, 'previewJapanWarehouseImport']);
    $router->post('/import-export/jp-warehouse/import', [$importExportController, 'importJapanWarehouse']);
    $router->post('/import-export/external-insert/preview', [$importExportController, 'externalInsertPreview']);
    $router->post('/import-export/external-insert/import', [$importExportController, 'externalInsertImport']);
    $router->get('/media', [$settingsController, 'media']);
    $router->get('/jobs', [$settingsController, 'jobs']);
    $router->get('/logs', [$settingsController, 'logs']);
    $router->get('/billing', [$settingsController, 'billing']);
    $router->get('/settings', [$settingsController, 'settings']);
    $router->post('/settings/save', [$settingsController, 'saveSettings']);
    $router->post('/settings/purchase-statuses/save', [$settingsController, 'savePurchaseStatuses']);
    $router->get('/stores', [$storeController, 'stores']);
    $router->post('/stores/add', [$storeController, 'addStore']);
    $router->get('/stores/edit', [$storeController, 'editStore']);
    $router->post('/stores/update', [$storeController, 'updateStore']);
    $router->get('/stores/yahoo/authorize', [$storeController, 'authorizeYahooShop']);
    $router->get('/oauth/yahoo/callback', [$storeController, 'yahooOAuthCallback']);
    $router->get('/users', [$userController, 'users']);
    $router->post('/users/add', [$userController, 'addUser']);
    $router->get('/users/edit', [$userController, 'editUser']);
    $router->post('/users/update', [$userController, 'updateUser']);
    $router->get('/password/edit', [$authController, 'passwordEdit']);
    $router->post('/password/update', [$authController, 'passwordUpdate']);
    $router->get('/notices', [$settingsController, 'tenantNotices']);
    $router->get('/notices/edit', [$settingsController, 'tenantNotices']);
    $router->post('/notices/save', [$settingsController, 'saveTenantNotice']);
    $router->post('/notices/delete', [$settingsController, 'deleteTenantNotice']);
    $router->post('/notices/pin', [$settingsController, 'pinTenantNotice']);
    $router->get('/users/permissions', [$userController, 'userPermissions']);
    $router->post('/users/permissions/save', [$userController, 'saveUserPermissions']);
    $router->get('/users/customer-service-deductions', [$userController, 'customerServiceDeductions']);
    $router->post('/users/customer-service-deductions/save', [$userController, 'saveCustomerServiceDeductions']);
    $router->get('/assignments', [$userController, 'assignments']);
    $router->post('/assignments/save', [$userController, 'saveAssignment']);
    $router->get('/orders/ajax/row', [$orderAjaxController, 'ajaxOrderRow']);
    $router->get('/orders/ajax/detail', [$orderAjaxController, 'ajaxOrderDetail']);
    $router->get('/orders/ajax/logistics', [$orderAjaxController, 'ajaxLogisticsReload']);
    $router->post('/orders/ajax/review', [$orderAjaxController, 'ajaxToggleReview']);
};
